services:
  mitmproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mitmproxy
    command: mitmdump -s /etc/scripts/adblock.py
    volumes:
      - ./config:/home/mitmproxy/.mitmproxy
      - ./scripts:/etc/scripts
      - ./filters:/etc/filters
      - ./logs:/var/log/mitmproxy-adblock
    ports:
      - "8118:8080"
    restart: unless-stopped
